Repository hamler-lang/hamler.github.io, pull requests merged in 2020-06, with the labels that each got.

#34 fix(fonts): Using Google Robot fonts without mistakes
  _layouts/default.html
  assets/css/style.scss
Labels: bug

#35 docs(index): update 'Features' block
  index.md
Labels: enhancement

#38 docs(index): update 'Documentation' paragraph
  index.md
Labels: documentation
